/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiIndexStreamJobIdRouteImport } from './routes/api/index-stream.$jobId'
import { Route as ApiConnectionsStatusRouteImport } from './routes/api/connections.status'
import { Route as AppHarnessesHarnessIdRouteImport } from './routes/_app/harnesses/$harnessId'
import { Route as AppExperimentsExperimentIdRouteImport } from './routes/_app/experiments/$experimentId'
import { Route as ApiExperimentsExperimentIdChatRouteImport } from './routes/api/experiments.$experimentId.chat'
import { Route as ApiExperimentsExperimentIdChatCancelRouteImport } from './routes/api/experiments.$experimentId.chat.cancel'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiIndexStreamJobIdRoute = ApiIndexStreamJobIdRouteImport.update({
  id: '/api/index-stream/$jobId',
  path: '/api/index-stream/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsStatusRoute = ApiConnectionsStatusRouteImport.update({
  id: '/api/connections/status',
  path: '/api/connections/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHarnessesHarnessIdRoute = AppHarnessesHarnessIdRouteImport.update({
  id: '/harnesses/$harnessId',
  path: '/harnesses/$harnessId',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsExperimentIdRoute =
  AppExperimentsExperimentIdRouteImport.update({
    id: '/experiments/$experimentId',
    path: '/experiments/$experimentId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiExperimentsExperimentIdChatRoute =
  ApiExperimentsExperimentIdChatRouteImport.update({
    id: '/api/experiments/$experimentId/chat',
    path: '/api/experiments/$experimentId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExperimentsExperimentIdChatCancelRoute =
  ApiExperimentsExperimentIdChatCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiExperimentsExperimentIdChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/experiments/$experimentId': typeof AppExperimentsExperimentIdRoute
  '/harnesses/$harnessId': typeof AppHarnessesHarnessIdRoute
  '/api/connections/status': typeof ApiConnectionsStatusRoute
  '/api/index-stream/$jobId': typeof ApiIndexStreamJobIdRoute
  '/api/experiments/$experimentId/chat': typeof ApiExperimentsExperimentIdChatRouteWithChildren
  '/api/experiments/$experimentId/chat/cancel': typeof ApiExperimentsExperimentIdChatCancelRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/experiments/$experimentId': typeof AppExperimentsExperimentIdRoute
  '/harnesses/$harnessId': typeof AppHarnessesHarnessIdRoute
  '/api/connections/status': typeof ApiConnectionsStatusRoute
  '/api/index-stream/$jobId': typeof ApiIndexStreamJobIdRoute
  '/api/experiments/$experimentId/chat': typeof ApiExperimentsExperimentIdChatRouteWithChildren
  '/api/experiments/$experimentId/chat/cancel': typeof ApiExperimentsExperimentIdChatCancelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/experiments/$experimentId': typeof AppExperimentsExperimentIdRoute
  '/_app/harnesses/$harnessId': typeof AppHarnessesHarnessIdRoute
  '/api/connections/status': typeof ApiConnectionsStatusRoute
  '/api/index-stream/$jobId': typeof ApiIndexStreamJobIdRoute
  '/api/experiments/$experimentId/chat': typeof ApiExperimentsExperimentIdChatRouteWithChildren
  '/api/experiments/$experimentId/chat/cancel': typeof ApiExperimentsExperimentIdChatCancelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiments/$experimentId'
    | '/harnesses/$harnessId'
    | '/api/connections/status'
    | '/api/index-stream/$jobId'
    | '/api/experiments/$experimentId/chat'
    | '/api/experiments/$experimentId/chat/cancel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiments/$experimentId'
    | '/harnesses/$harnessId'
    | '/api/connections/status'
    | '/api/index-stream/$jobId'
    | '/api/experiments/$experimentId/chat'
    | '/api/experiments/$experimentId/chat/cancel'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/experiments/$experimentId'
    | '/_app/harnesses/$harnessId'
    | '/api/connections/status'
    | '/api/index-stream/$jobId'
    | '/api/experiments/$experimentId/chat'
    | '/api/experiments/$experimentId/chat/cancel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiConnectionsStatusRoute: typeof ApiConnectionsStatusRoute
  ApiIndexStreamJobIdRoute: typeof ApiIndexStreamJobIdRoute
  ApiExperimentsExperimentIdChatRoute: typeof ApiExperimentsExperimentIdChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/index-stream/$jobId': {
      id: '/api/index-stream/$jobId'
      path: '/api/index-stream/$jobId'
      fullPath: '/api/index-stream/$jobId'
      preLoaderRoute: typeof ApiIndexStreamJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/status': {
      id: '/api/connections/status'
      path: '/api/connections/status'
      fullPath: '/api/connections/status'
      preLoaderRoute: typeof ApiConnectionsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/harnesses/$harnessId': {
      id: '/_app/harnesses/$harnessId'
      path: '/harnesses/$harnessId'
      fullPath: '/harnesses/$harnessId'
      preLoaderRoute: typeof AppHarnessesHarnessIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experiments/$experimentId': {
      id: '/_app/experiments/$experimentId'
      path: '/experiments/$experimentId'
      fullPath: '/experiments/$experimentId'
      preLoaderRoute: typeof AppExperimentsExperimentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/experiments/$experimentId/chat': {
      id: '/api/experiments/$experimentId/chat'
      path: '/api/experiments/$experimentId/chat'
      fullPath: '/api/experiments/$experimentId/chat'
      preLoaderRoute: typeof ApiExperimentsExperimentIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiments/$experimentId/chat/cancel': {
      id: '/api/experiments/$experimentId/chat/cancel'
      path: '/cancel'
      fullPath: '/api/experiments/$experimentId/chat/cancel'
      preLoaderRoute: typeof ApiExperimentsExperimentIdChatCancelRouteImport
      parentRoute: typeof ApiExperimentsExperimentIdChatRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppExperimentsExperimentIdRoute: typeof AppExperimentsExperimentIdRoute
  AppHarnessesHarnessIdRoute: typeof AppHarnessesHarnessIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppExperimentsExperimentIdRoute: AppExperimentsExperimentIdRoute,
  AppHarnessesHarnessIdRoute: AppHarnessesHarnessIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiExperimentsExperimentIdChatRouteChildren {
  ApiExperimentsExperimentIdChatCancelRoute: typeof ApiExperimentsExperimentIdChatCancelRoute
}

const ApiExperimentsExperimentIdChatRouteChildren: ApiExperimentsExperimentIdChatRouteChildren =
  {
    ApiExperimentsExperimentIdChatCancelRoute:
      ApiExperimentsExperimentIdChatCancelRoute,
  }

const ApiExperimentsExperimentIdChatRouteWithChildren =
  ApiExperimentsExperimentIdChatRoute._addFileChildren(
    ApiExperimentsExperimentIdChatRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiConnectionsStatusRoute: ApiConnectionsStatusRoute,
  ApiIndexStreamJobIdRoute: ApiIndexStreamJobIdRoute,
  ApiExperimentsExperimentIdChatRoute:
    ApiExperimentsExperimentIdChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
